services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules  # Evita sobreescribir node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped  # Reinicia automáticamente si falla
    command: npm run dev     # Sobreescribe el comando por defecto
    depends_on:
      - mongo  # Espera a que MongoDB esté listo antes de iniciar la API

  mongo:
    image: mongo  # Imagen oficial de MongoDB
    container_name: mongo  # Nombre del contenedor
    restart: always  # Reinicia siempre el contenedor
    ports:
      - "27017:27017"  # Puerto de MongoDB
    volumes:
      - mongo-data:/data/db  # Persistencia de datos de MongoDB

volumes:
  mongo-data:  # Volumen para persistencia de datos de MongoDB
